version: "3.3"
services:
  studente1:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "100:80"
    volumes: 
      - /dev/shm:/dev/shm
    environment:
      - USER=net
      - PASSWORD=work
      - HTTP_PASSWORD=work
    command: bash -c "apt update && apt upgrade && apt install dsniff"

